spring:
  application:
    name: before-you-bet


api-data:
  url: https://v3.football.api-sports.io
  key: 

season:
  year: 2022

cors:
  allowed:
    - http://localhost:5173
    - https://before-you-bet.com
    - https://www.before-you-bet.com