spring:
  application:
    name: match-insights-api
  data:
    redis:
      host: localhost
      port: 6379

api-data:
  url:
  key:

season:
  year:
  worldCupYear: 2026

cors:
  allowed:
    - http://localhost:5173
    - https://matchinsights.info
    - https://www.matchinsights.info