spring:
  application:
    name: match-insights-api
  redis:
    host: redis
    port: 6379

api-data:
  url:
  key:

season:
  year:

cors:
  allowed:
    - http://localhost:5173
    - https://matchinsights.info
    - https://www.matchinsights.info