spring:
  application:
    name: before-you-bet
  redis:
    host: localhost
    port: 6379
    timeout: 60000

api-data:
  url:
  key:

season:
  year: 2022

cors:
  allowed:
    - http://localhost:5173
    - https://before-you-bet.com
    - https://www.before-you-bet.com