services:
  redis:
    image: redis:7-alpine
    container_name: redis_local
    ports:
      - "6379:6379"
    restart: unless-stopped

# commands
# docker compose -f ... up
# docker exec -it redis_local redis-cli